from typing import Iterable

class BloomFilter:
    capacity: int
    fp_rate: float
    k: int
    byte_count: int
    bit_count: int
    
    def __init__(self, capacity: int, fp_rate: float = 0.01) -> None: ...
    def add(self, item: object) -> None: ...
    def update(self, items: Iterable[object]) -> None: ...
    def __contains__(self, item: object) -> bool: ...
    def __len__(self) -> int: ...
